# For more information: https://laravel.com/docs/sail
version: '3'
services:
  #frontend
  app:
    container_name: ${GROUP_NAME}-app
    image: node:14.15.4-alpine3.12
    working_dir: /usr/src/app
    ports:
      - ${APP_PORT:-80}:8080
    environment:
      APP_DEBUG: ${APP_DEBUG}
      APP_NAME: ${APP_NAME}
    volumes:
      - ${APP_PATH}:/usr/src/app
    command: "sh start"
    # networks:
    #   - algebranation

# networks:
#   algebranation:
#     driver: bridge
