#!/bin/bash

[ ! -d "./node_modules" ] && yarn install

mode="serve"
if [ -d "./node_modules" ]; then
   case "$1" in
      build ) mode="build";;
      false ) mode="build";;
      p ) mode="build";;
      prod ) mode="build";;
   esac
fi
yarn $mode
